name: Generate Directory Contents JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-directory-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Generate Directory Contents JSON
      run: |
        python3 << EOF
import os
import json

def get_directory_contents(directory):
    contents = []
    # Exclude certain directories and files
    exclude_dirs = ['.git', '.github', '.vscode']
    exclude_files = ['.gitignore', 'directory-contents.json']
    
    for item in os.scandir(directory):
        # Skip excluded directories and files
        if item.name in exclude_dirs or item.name in exclude_files:
            continue
        
        try:
            entry = {
                'name': item.name,
                'is_dir': item.is_dir()
            }
            if not item.is_dir():
                entry['size_bytes'] = item.stat().st_size
            contents.append(entry)
        except Exception as e:
            print(f"Could not process {item.name}: {e}")
    
    return contents

def main():
    # Get the current directory
    current_dir = os.path.dirname(os.path.abspath('.'))
    
    # Get directory contents
    contents = get_directory_contents(current_dir)
    
    # Write to JSON file
    with open('directory-contents.json', 'w') as f:
        json.dump(contents, f, indent=2)

if __name__ == '__main__':
    main()
EOF
    
    - name: Commit and push if changed
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add directory-contents.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update directory contents JSON"
        git push
